version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - abresani_static_volume:/abresani/static
      - abresani_files_volume:/abresani/files
      - fars_habitat_static_volume:/fars_habitat/static
      - fars_habitat_files_volume:/fars_habitat/files
    networks:
      - nginx_network

volumes:
  abresani_static_volume:
    external: true
  abresani_files_volume:
    external: true
  fars_habitat_static_volume:
    external: true
  fars_habitat_files_volume:
    external: true
networks:
  nginx_network:
    external: true