# Generated by Django 4.0.4 on 2022-07-19 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=202, verbose_name='نام دپارتمان')),
                ('Desc', models.TextField(default='', verbose_name='یادداشت')),
                ('UserGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='گروه کاربری')),
            ],
            options={
                'verbose_name': 'دپارتمان',
                'verbose_name_plural': 'دپارتمان',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=202, verbose_name='موضوع')),
                ('Zaman', models.CharField(max_length=202, verbose_name='زمان آخرین تغییر')),
                ('Attachments', models.ImageField(default='', upload_to='files/images/ticket-attachs', verbose_name='پیوست')),
                ('Note', models.TextField(default='', verbose_name='یادداشت مدیریت')),
                ('RelatedDepartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.department', verbose_name='دپارتمان')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': 'تیکت',
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField(default='', verbose_name='متن تیکت')),
                ('Tarikh', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ')),
                ('Attachments', models.ImageField(default='', upload_to='files/images/ticket-attachs', verbose_name='پیوست')),
                ('RelatedTicket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.ticket', verbose_name='مربوط به تیکت')),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': 'تیکت',
            },
        ),
    ]
