# Generated by Django 4.0.4 on 2022-07-19 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketmessage',
            options={'verbose_name': 'پیام ها', 'verbose_name_plural': 'پیام ها'},
        ),
    ]
